ALTER TYPE "CouponRuleType" ADD VALUE IF NOT EXISTS 'TARGET_CATEGORY';
ALTER TYPE "CouponRuleType" ADD VALUE IF NOT EXISTS 'TARGET_PRODUCT_ID';
ALTER TYPE "CouponRuleType" ADD VALUE IF NOT EXISTS 'DECORATION_REQUIRED';
